/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.yams.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ActionLog service. Represents a row in the &quot;yams_ActionLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gnenc.yams.model.impl.ActionLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gnenc.yams.model.impl.ActionLogImpl}.
 * </p>
 *
 * @author Drew A. Blessing
 * @see ActionLog
 * @see org.gnenc.yams.model.impl.ActionLogImpl
 * @see org.gnenc.yams.model.impl.ActionLogModelImpl
 * @generated
 */
public interface ActionLogModel extends BaseModel<ActionLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a action log model instance should use the {@link ActionLog} interface instead.
	 */

	/**
	 * Returns the primary key of this action log.
	 *
	 * @return the primary key of this action log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this action log.
	 *
	 * @param primaryKey the primary key of this action log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this action log.
	 *
	 * @return the ID of this action log
	 */
	public long getId();

	/**
	 * Sets the ID of this action log.
	 *
	 * @param id the ID of this action log
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this action log.
	 *
	 * @return the company ID of this action log
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this action log.
	 *
	 * @param companyId the company ID of this action log
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this action log.
	 *
	 * @return the user ID of this action log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this action log.
	 *
	 * @param userId the user ID of this action log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this action log.
	 *
	 * @return the user uuid of this action log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this action log.
	 *
	 * @param userUuid the user uuid of this action log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this action log.
	 *
	 * @return the user name of this action log
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this action log.
	 *
	 * @param userName the user name of this action log
	 */
	public void setUserName(String userName);

	/**
	 * Returns the modified date of this action log.
	 *
	 * @return the modified date of this action log
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this action log.
	 *
	 * @param modifiedDate the modified date of this action log
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user email address of this action log.
	 *
	 * @return the user email address of this action log
	 */
	@AutoEscape
	public String getUserEmailAddress();

	/**
	 * Sets the user email address of this action log.
	 *
	 * @param userEmailAddress the user email address of this action log
	 */
	public void setUserEmailAddress(String userEmailAddress);

	/**
	 * Returns the modified user ID of this action log.
	 *
	 * @return the modified user ID of this action log
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this action log.
	 *
	 * @param modifiedUserId the modified user ID of this action log
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this action log.
	 *
	 * @return the modified user uuid of this action log
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this action log.
	 *
	 * @param modifiedUserUuid the modified user uuid of this action log
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this action log.
	 *
	 * @return the modified user name of this action log
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this action log.
	 *
	 * @param modifiedUserName the modified user name of this action log
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the modified user email address of this action log.
	 *
	 * @return the modified user email address of this action log
	 */
	@AutoEscape
	public String getModifiedUserEmailAddress();

	/**
	 * Sets the modified user email address of this action log.
	 *
	 * @param modifiedUserEmailAddress the modified user email address of this action log
	 */
	public void setModifiedUserEmailAddress(String modifiedUserEmailAddress);

	/**
	 * Returns the modified description of this action log.
	 *
	 * @return the modified description of this action log
	 */
	@AutoEscape
	public String getModifiedDescription();

	/**
	 * Sets the modified description of this action log.
	 *
	 * @param modifiedDescription the modified description of this action log
	 */
	public void setModifiedDescription(String modifiedDescription);

	/**
	 * Returns the modified fqgn of this action log.
	 *
	 * @return the modified fqgn of this action log
	 */
	@AutoEscape
	public String getModifiedFqgn();

	/**
	 * Sets the modified fqgn of this action log.
	 *
	 * @param modifiedFqgn the modified fqgn of this action log
	 */
	public void setModifiedFqgn(String modifiedFqgn);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ActionLog actionLog);

	public int hashCode();

	public CacheModel<ActionLog> toCacheModel();

	public ActionLog toEscapedModel();

	public String toString();

	public String toXmlString();
}