/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.yams.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobQueue service. Represents a row in the &quot;yams_JobQueue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gnenc.yams.model.impl.JobQueueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gnenc.yams.model.impl.JobQueueImpl}.
 * </p>
 *
 * @author Drew A. Blessing
 * @see JobQueue
 * @see org.gnenc.yams.model.impl.JobQueueImpl
 * @see org.gnenc.yams.model.impl.JobQueueModelImpl
 * @generated
 */
public interface JobQueueModel extends BaseModel<JobQueue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job queue model instance should use the {@link JobQueue} interface instead.
	 */

	/**
	 * Returns the primary key of this job queue.
	 *
	 * @return the primary key of this job queue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job queue.
	 *
	 * @param primaryKey the primary key of this job queue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this job queue.
	 *
	 * @return the ID of this job queue
	 */
	public long getId();

	/**
	 * Sets the ID of this job queue.
	 *
	 * @param id the ID of this job queue
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this job queue.
	 *
	 * @return the company ID of this job queue
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this job queue.
	 *
	 * @param companyId the company ID of this job queue
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this job queue.
	 *
	 * @return the user ID of this job queue
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this job queue.
	 *
	 * @param userId the user ID of this job queue
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job queue.
	 *
	 * @return the user uuid of this job queue
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job queue.
	 *
	 * @param userUuid the user uuid of this job queue
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this job queue.
	 *
	 * @return the user name of this job queue
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this job queue.
	 *
	 * @param userName the user name of this job queue
	 */
	public void setUserName(String userName);

	/**
	 * Returns the modified date of this job queue.
	 *
	 * @return the modified date of this job queue
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job queue.
	 *
	 * @param modifiedDate the modified date of this job queue
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user email address of this job queue.
	 *
	 * @return the user email address of this job queue
	 */
	@AutoEscape
	public String getUserEmailAddress();

	/**
	 * Sets the user email address of this job queue.
	 *
	 * @param userEmailAddress the user email address of this job queue
	 */
	public void setUserEmailAddress(String userEmailAddress);

	/**
	 * Returns the job user ID of this job queue.
	 *
	 * @return the job user ID of this job queue
	 */
	public long getJobUserId();

	/**
	 * Sets the job user ID of this job queue.
	 *
	 * @param jobUserId the job user ID of this job queue
	 */
	public void setJobUserId(long jobUserId);

	/**
	 * Returns the job user uuid of this job queue.
	 *
	 * @return the job user uuid of this job queue
	 * @throws SystemException if a system exception occurred
	 */
	public String getJobUserUuid() throws SystemException;

	/**
	 * Sets the job user uuid of this job queue.
	 *
	 * @param jobUserUuid the job user uuid of this job queue
	 */
	public void setJobUserUuid(String jobUserUuid);

	/**
	 * Returns the job user name of this job queue.
	 *
	 * @return the job user name of this job queue
	 */
	@AutoEscape
	public String getJobUserName();

	/**
	 * Sets the job user name of this job queue.
	 *
	 * @param jobUserName the job user name of this job queue
	 */
	public void setJobUserName(String jobUserName);

	/**
	 * Returns the job user email address of this job queue.
	 *
	 * @return the job user email address of this job queue
	 */
	@AutoEscape
	public String getJobUserEmailAddress();

	/**
	 * Sets the job user email address of this job queue.
	 *
	 * @param jobUserEmailAddress the job user email address of this job queue
	 */
	public void setJobUserEmailAddress(String jobUserEmailAddress);

	/**
	 * Returns the job description of this job queue.
	 *
	 * @return the job description of this job queue
	 */
	@AutoEscape
	public String getJobDescription();

	/**
	 * Sets the job description of this job queue.
	 *
	 * @param jobDescription the job description of this job queue
	 */
	public void setJobDescription(String jobDescription);

	/**
	 * Returns the job action of this job queue.
	 *
	 * @return the job action of this job queue
	 */
	@AutoEscape
	public String getJobAction();

	/**
	 * Sets the job action of this job queue.
	 *
	 * @param jobAction the job action of this job queue
	 */
	public void setJobAction(String jobAction);

	/**
	 * Returns the job date of this job queue.
	 *
	 * @return the job date of this job queue
	 */
	public Date getJobDate();

	/**
	 * Sets the job date of this job queue.
	 *
	 * @param jobDate the job date of this job queue
	 */
	public void setJobDate(Date jobDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(JobQueue jobQueue);

	public int hashCode();

	public CacheModel<JobQueue> toCacheModel();

	public JobQueue toEscapedModel();

	public String toString();

	public String toXmlString();
}