/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.yams.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Permissions service. Represents a row in the &quot;yams_Permissions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.gnenc.yams.model.impl.PermissionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.gnenc.yams.model.impl.PermissionsImpl}.
 * </p>
 *
 * @author Drew A. Blessing
 * @see Permissions
 * @see org.gnenc.yams.model.impl.PermissionsImpl
 * @see org.gnenc.yams.model.impl.PermissionsModelImpl
 * @generated
 */
public interface PermissionsModel extends AuditedModel, BaseModel<Permissions> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permissions model instance should use the {@link Permissions} interface instead.
	 */

	/**
	 * Returns the primary key of this permissions.
	 *
	 * @return the primary key of this permissions
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permissions.
	 *
	 * @param primaryKey the primary key of this permissions
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this permissions.
	 *
	 * @return the ID of this permissions
	 */
	public long getId();

	/**
	 * Sets the ID of this permissions.
	 *
	 * @param id the ID of this permissions
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this permissions.
	 *
	 * @return the company ID of this permissions
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this permissions.
	 *
	 * @param companyId the company ID of this permissions
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this permissions.
	 *
	 * @return the user ID of this permissions
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this permissions.
	 *
	 * @param userId the user ID of this permissions
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this permissions.
	 *
	 * @return the user uuid of this permissions
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this permissions.
	 *
	 * @param userUuid the user uuid of this permissions
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this permissions.
	 *
	 * @return the user name of this permissions
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this permissions.
	 *
	 * @param userName the user name of this permissions
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this permissions.
	 *
	 * @return the create date of this permissions
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this permissions.
	 *
	 * @param createDate the create date of this permissions
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this permissions.
	 *
	 * @return the modified date of this permissions
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this permissions.
	 *
	 * @param modifiedDate the modified date of this permissions
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email address of this permissions.
	 *
	 * @return the email address of this permissions
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this permissions.
	 *
	 * @param emailAddress the email address of this permissions
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the fqgn of this permissions.
	 *
	 * @return the fqgn of this permissions
	 */
	@AutoEscape
	public String getFqgn();

	/**
	 * Sets the fqgn of this permissions.
	 *
	 * @param fqgn the fqgn of this permissions
	 */
	public void setFqgn(String fqgn);

	/**
	 * Returns the permissions of this permissions.
	 *
	 * @return the permissions of this permissions
	 */
	public long getPermissions();

	/**
	 * Sets the permissions of this permissions.
	 *
	 * @param permissions the permissions of this permissions
	 */
	public void setPermissions(long permissions);

	/**
	 * Returns the permissions grantable of this permissions.
	 *
	 * @return the permissions grantable of this permissions
	 */
	public long getPermissionsGrantable();

	/**
	 * Sets the permissions grantable of this permissions.
	 *
	 * @param permissionsGrantable the permissions grantable of this permissions
	 */
	public void setPermissionsGrantable(long permissionsGrantable);

	/**
	 * Returns the group permission of this permissions.
	 *
	 * @return the group permission of this permissions
	 */
	public boolean getGroupPermission();

	/**
	 * Returns <code>true</code> if this permissions is group permission.
	 *
	 * @return <code>true</code> if this permissions is group permission; <code>false</code> otherwise
	 */
	public boolean isGroupPermission();

	/**
	 * Sets whether this permissions is group permission.
	 *
	 * @param groupPermission the group permission of this permissions
	 */
	public void setGroupPermission(boolean groupPermission);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Permissions permissions);

	public int hashCode();

	public CacheModel<Permissions> toCacheModel();

	public Permissions toEscapedModel();

	public String toString();

	public String toXmlString();
}