/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.yams.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.gnenc.yams.model.ActionLog;
import org.gnenc.yams.service.ActionLogLocalService;
import org.gnenc.yams.service.JobQueueLocalService;
import org.gnenc.yams.service.PermissionsDefinedLocalService;
import org.gnenc.yams.service.PermissionsLocalService;
import org.gnenc.yams.service.persistence.ActionLogPersistence;
import org.gnenc.yams.service.persistence.JobQueuePersistence;
import org.gnenc.yams.service.persistence.PermissionsDefinedPersistence;
import org.gnenc.yams.service.persistence.PermissionsPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the action log local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.gnenc.yams.service.impl.ActionLogLocalServiceImpl}.
 * </p>
 *
 * @author Drew A. Blessing
 * @see org.gnenc.yams.service.impl.ActionLogLocalServiceImpl
 * @see org.gnenc.yams.service.ActionLogLocalServiceUtil
 * @generated
 */
public abstract class ActionLogLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements ActionLogLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.gnenc.yams.service.ActionLogLocalServiceUtil} to access the action log local service.
	 */

	/**
	 * Adds the action log to the database. Also notifies the appropriate model listeners.
	 *
	 * @param actionLog the action log
	 * @return the action log that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public ActionLog addActionLog(ActionLog actionLog)
		throws SystemException {
		actionLog.setNew(true);

		return actionLogPersistence.update(actionLog, false);
	}

	/**
	 * Creates a new action log with the primary key. Does not add the action log to the database.
	 *
	 * @param id the primary key for the new action log
	 * @return the new action log
	 */
	public ActionLog createActionLog(long id) {
		return actionLogPersistence.create(id);
	}

	/**
	 * Deletes the action log with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the action log
	 * @return the action log that was removed
	 * @throws PortalException if a action log with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public ActionLog deleteActionLog(long id)
		throws PortalException, SystemException {
		return actionLogPersistence.remove(id);
	}

	/**
	 * Deletes the action log from the database. Also notifies the appropriate model listeners.
	 *
	 * @param actionLog the action log
	 * @return the action log that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public ActionLog deleteActionLog(ActionLog actionLog)
		throws SystemException {
		return actionLogPersistence.remove(actionLog);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ActionLog.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return actionLogPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return actionLogPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return actionLogPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return actionLogPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public ActionLog fetchActionLog(long id) throws SystemException {
		return actionLogPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the action log with the primary key.
	 *
	 * @param id the primary key of the action log
	 * @return the action log
	 * @throws PortalException if a action log with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ActionLog getActionLog(long id)
		throws PortalException, SystemException {
		return actionLogPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return actionLogPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the action logs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of action logs
	 * @param end the upper bound of the range of action logs (not inclusive)
	 * @return the range of action logs
	 * @throws SystemException if a system exception occurred
	 */
	public List<ActionLog> getActionLogs(int start, int end)
		throws SystemException {
		return actionLogPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of action logs.
	 *
	 * @return the number of action logs
	 * @throws SystemException if a system exception occurred
	 */
	public int getActionLogsCount() throws SystemException {
		return actionLogPersistence.countAll();
	}

	/**
	 * Updates the action log in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param actionLog the action log
	 * @return the action log that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public ActionLog updateActionLog(ActionLog actionLog)
		throws SystemException {
		return updateActionLog(actionLog, true);
	}

	/**
	 * Updates the action log in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param actionLog the action log
	 * @param merge whether to merge the action log with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the action log that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public ActionLog updateActionLog(ActionLog actionLog, boolean merge)
		throws SystemException {
		actionLog.setNew(false);

		return actionLogPersistence.update(actionLog, merge);
	}

	/**
	 * Returns the action log local service.
	 *
	 * @return the action log local service
	 */
	public ActionLogLocalService getActionLogLocalService() {
		return actionLogLocalService;
	}

	/**
	 * Sets the action log local service.
	 *
	 * @param actionLogLocalService the action log local service
	 */
	public void setActionLogLocalService(
		ActionLogLocalService actionLogLocalService) {
		this.actionLogLocalService = actionLogLocalService;
	}

	/**
	 * Returns the action log persistence.
	 *
	 * @return the action log persistence
	 */
	public ActionLogPersistence getActionLogPersistence() {
		return actionLogPersistence;
	}

	/**
	 * Sets the action log persistence.
	 *
	 * @param actionLogPersistence the action log persistence
	 */
	public void setActionLogPersistence(
		ActionLogPersistence actionLogPersistence) {
		this.actionLogPersistence = actionLogPersistence;
	}

	/**
	 * Returns the job queue local service.
	 *
	 * @return the job queue local service
	 */
	public JobQueueLocalService getJobQueueLocalService() {
		return jobQueueLocalService;
	}

	/**
	 * Sets the job queue local service.
	 *
	 * @param jobQueueLocalService the job queue local service
	 */
	public void setJobQueueLocalService(
		JobQueueLocalService jobQueueLocalService) {
		this.jobQueueLocalService = jobQueueLocalService;
	}

	/**
	 * Returns the job queue persistence.
	 *
	 * @return the job queue persistence
	 */
	public JobQueuePersistence getJobQueuePersistence() {
		return jobQueuePersistence;
	}

	/**
	 * Sets the job queue persistence.
	 *
	 * @param jobQueuePersistence the job queue persistence
	 */
	public void setJobQueuePersistence(JobQueuePersistence jobQueuePersistence) {
		this.jobQueuePersistence = jobQueuePersistence;
	}

	/**
	 * Returns the permissions local service.
	 *
	 * @return the permissions local service
	 */
	public PermissionsLocalService getPermissionsLocalService() {
		return permissionsLocalService;
	}

	/**
	 * Sets the permissions local service.
	 *
	 * @param permissionsLocalService the permissions local service
	 */
	public void setPermissionsLocalService(
		PermissionsLocalService permissionsLocalService) {
		this.permissionsLocalService = permissionsLocalService;
	}

	/**
	 * Returns the permissions persistence.
	 *
	 * @return the permissions persistence
	 */
	public PermissionsPersistence getPermissionsPersistence() {
		return permissionsPersistence;
	}

	/**
	 * Sets the permissions persistence.
	 *
	 * @param permissionsPersistence the permissions persistence
	 */
	public void setPermissionsPersistence(
		PermissionsPersistence permissionsPersistence) {
		this.permissionsPersistence = permissionsPersistence;
	}

	/**
	 * Returns the permissions defined local service.
	 *
	 * @return the permissions defined local service
	 */
	public PermissionsDefinedLocalService getPermissionsDefinedLocalService() {
		return permissionsDefinedLocalService;
	}

	/**
	 * Sets the permissions defined local service.
	 *
	 * @param permissionsDefinedLocalService the permissions defined local service
	 */
	public void setPermissionsDefinedLocalService(
		PermissionsDefinedLocalService permissionsDefinedLocalService) {
		this.permissionsDefinedLocalService = permissionsDefinedLocalService;
	}

	/**
	 * Returns the permissions defined persistence.
	 *
	 * @return the permissions defined persistence
	 */
	public PermissionsDefinedPersistence getPermissionsDefinedPersistence() {
		return permissionsDefinedPersistence;
	}

	/**
	 * Sets the permissions defined persistence.
	 *
	 * @param permissionsDefinedPersistence the permissions defined persistence
	 */
	public void setPermissionsDefinedPersistence(
		PermissionsDefinedPersistence permissionsDefinedPersistence) {
		this.permissionsDefinedPersistence = permissionsDefinedPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("org.gnenc.yams.model.ActionLog",
			actionLogLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.gnenc.yams.model.ActionLog");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return ActionLog.class;
	}

	protected String getModelClassName() {
		return ActionLog.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = actionLogPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ActionLogLocalService.class)
	protected ActionLogLocalService actionLogLocalService;
	@BeanReference(type = ActionLogPersistence.class)
	protected ActionLogPersistence actionLogPersistence;
	@BeanReference(type = JobQueueLocalService.class)
	protected JobQueueLocalService jobQueueLocalService;
	@BeanReference(type = JobQueuePersistence.class)
	protected JobQueuePersistence jobQueuePersistence;
	@BeanReference(type = PermissionsLocalService.class)
	protected PermissionsLocalService permissionsLocalService;
	@BeanReference(type = PermissionsPersistence.class)
	protected PermissionsPersistence permissionsPersistence;
	@BeanReference(type = PermissionsDefinedLocalService.class)
	protected PermissionsDefinedLocalService permissionsDefinedLocalService;
	@BeanReference(type = PermissionsDefinedPersistence.class)
	protected PermissionsDefinedPersistence permissionsDefinedPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ActionLogLocalServiceClpInvoker _clpInvoker = new ActionLogLocalServiceClpInvoker();
}