/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.gnenc.yams.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.gnenc.yams.model.Permissions;
import org.gnenc.yams.service.PermissionsLocalServiceUtil;

/**
 * The extended model base implementation for the Permissions service. Represents a row in the &quot;yams_Permissions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionsImpl}.
 * </p>
 *
 * @author Drew A. Blessing
 * @see PermissionsImpl
 * @see org.gnenc.yams.model.Permissions
 * @generated
 */
public abstract class PermissionsBaseImpl extends PermissionsModelImpl
	implements Permissions {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permissions model instance should use the {@link Permissions} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			PermissionsLocalServiceUtil.addPermissions(this);
		}
		else {
			PermissionsLocalServiceUtil.updatePermissions(this);
		}
	}
}